import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, ArrowRight, Check, Clock3, Code2, History, LoaderCircle, LockKeyhole, Search, Sparkles, X } from "lucide-react";
import { NavLink } from "react-router-dom";
import { api, type AlphaCandidate, type AlphaFeature, type StrategyVersion, type Workspace } from "./api";
import "./AlphaStudio.css";

type Props = { workspace: Workspace; workspaces: Workspace[]; offline: boolean; hashPinnedExtensionsEnabled?: boolean };
const PythonEditor = lazy(() => import("./PythonEditor"));
const demoFeatures: AlphaFeature[] = [
  { name: "graph_ripple_risk", category: "Graph · propagation", description: "Weighted downstream exposure from eligible relationships.", available: true, frequency: 0.91, provenance: ["Graph snapshot", "Deterministic feature receipt"], readiness: "ready", reason: null },
  { name: "dependency_strength", category: "Graph · relationships", description: "Aggregate confidence and economic exposure to direct suppliers.", available: true, frequency: 0.78, provenance: ["Cited relationships"], readiness: "ready", reason: null },
  { name: "market_return", category: "Market · returns", description: "Point-in-time adjusted return over the configured cadence.", available: false, frequency: null, provenance: [], readiness: "unavailable", reason: "No historical market panel is connected to this workspace." },
];
const starterCandidates: AlphaCandidate[] = [
  { candidate_id: "demo-1", name: "Ripple exposure", expression: "Rank(graph_ripple_risk)", rationale: "Tests whether network shock exposure has a cross-sectional signal.", feature_names: ["graph_ripple_risk"], status: "DEMO proposal" },
  { candidate_id: "demo-2", name: "Dependency quality", expression: "−Rank(dependency_strength)", rationale: "A simple comparator using direct dependency strength.", feature_names: ["dependency_strength"], status: "DEMO proposal" },
];

function records(value: Record<string, unknown> | undefined) { return value ?? {}; }
function formatFrequency(value: number | string | null) { return value === null ? "Not measured" : typeof value === "number" ? `${Math.round(value * 100)}% observed` : value; }

export function AlphaStudio({ workspace, workspaces, offline, hashPinnedExtensionsEnabled = false }: Props) {
  const client = useQueryClient();
  const [workspaceSelection, setWorkspaceSelection] = useState<string | null>(null);
  const workspaceId = workspaceSelection && workspaces.some((item) => item.workspace_id === workspaceSelection) ? workspaceSelection : workspace.workspace_id;
  const activeWorkspace = workspaces.find((item) => item.workspace_id === workspaceId) ?? workspace;
  const graphQuery = useQuery({ queryKey: ["graph-snapshots", workspaceId], queryFn: () => api.graphSnapshots(workspaceId), enabled: Boolean(workspaceId && activeWorkspace.universe_id), retry: false });
  const snapshotId = activeWorkspace.graph_version_id ?? graphQuery.data?.[0]?.snapshot_id ?? "";
  const featureQuery = useQuery({ queryKey: ["alpha-features", workspaceId, snapshotId], queryFn: () => api.alphaFeatures(workspaceId), enabled: Boolean(workspaceId && activeWorkspace.universe_id), retry: false });
  const strategiesQuery = useQuery({ queryKey: ["strategies", workspaceId], queryFn: () => api.strategies(workspaceId), enabled: Boolean(workspaceId && !offline), retry: false });
  const features = featureQuery.data ?? (featureQuery.isError || offline ? demoFeatures : []);
  const [intent, setIntent] = useState("Test whether supply-chain ripple risk explains next-period cross-sectional returns.");
  const [search, setSearch] = useState("");
  const [selectedFeatures, setSelectedFeatures] = useState<string[]>(["graph_ripple_risk", "dependency_strength"]);
  const [candidates, setCandidates] = useState<AlphaCandidate[]>(offline ? starterCandidates : []);
  const [selected, setSelected] = useState(0);
  const [expression, setExpression] = useState(offline ? starterCandidates[0].expression : "");
  const [strategyName, setStrategyName] = useState("Ripple risk strategy");
  const [saved, setSaved] = useState<StrategyVersion | null>(null);
  const [validation, setValidation] = useState<{ ok: boolean; message: string } | null>(null);
  const [errorMessage, setErrorMessage] = useState("");
  const [advanced, setAdvanced] = useState(false);
  const [pythonDraft, setPythonDraft] = useState("def transform(features):\n    return features\n");
  const [portfolio, setPortfolio] = useState({ weighting: "equal_weight", rebalance: "workspace cadence", max_positions: 25 });
  const [risk, setRisk] = useState({ max_position_weight: 0.1, max_turnover: 0.5, sector_neutral: true });
  const versionsQuery = useQuery({ queryKey: ["strategy-versions", saved?.strategy_id], queryFn: () => api.strategyVersions(saved!.strategy_id), enabled: Boolean(saved?.strategy_id), retry: false });
  const grouped = useMemo(() => {
    const filtered = features.filter((feature) => `${feature.name} ${feature.category} ${feature.description}`.toLowerCase().includes(search.toLowerCase()));
    return filtered.reduce<Record<string, AlphaFeature[]>>((result, feature) => { (result[feature.category] ??= []).push(feature); return result; }, {});
  }, [features, search]);
  useEffect(() => {
    if (!features.length) return;
    setSelectedFeatures((current) => {
      const available = new Set(features.filter((feature) => feature.available).map((feature) => feature.name));
      const retained = current.filter((name) => available.has(name));
      return retained.length ? retained : features.filter((feature) => feature.available).slice(0, 2).map((feature) => feature.name);
    });
  }, [features]);

  const generate = useMutation({ mutationFn: () => api.generateAlphaCandidates(workspaceId, { intent, feature_names: selectedFeatures.filter((name) => features.some((feature) => feature.name === name && feature.available)), universe_id: activeWorkspace.universe_id!, graph_snapshot_id: snapshotId, portfolio: records(portfolio), risk: records(risk) }), onSuccess: (items) => { setCandidates(items); setSelected(0); setExpression(items[0]?.expression ?? ""); setValidation(null); setErrorMessage(""); }, onError: (error) => setErrorMessage(error instanceof Error ? error.message : "Candidate generation failed.") });
  const validate = useMutation({ mutationFn: () => api.validateStrategy({ workspace_id: workspaceId, universe_id: activeWorkspace.universe_id, graph_snapshot_id: snapshotId, name: strategyName, expression, feature_names: selectedFeatures, portfolio, risk }), onSuccess: (result) => { const valid = result.valid === true || result.ok === true || result.status === "passed"; const checks = Array.isArray(result.checks) ? result.checks as Array<Record<string, unknown>> : []; const message = typeof result.message === "string" ? result.message : checks.map((check) => String(check.message ?? check.name ?? "Check complete")).join(" · ") || (valid ? "Deterministic contract checks passed." : "Validation returned without a passing status."); setValidation({ ok: valid, message }); setErrorMessage(""); }, onError: (error) => { setValidation({ ok: false, message: error instanceof Error ? error.message : "Validation failed." }); } });
  const save = useMutation({ mutationFn: () => api.saveStrategy(workspaceId, { strategy_id: saved?.strategy_id, name: strategyName, expression, feature_names: selectedFeatures, universe_id: activeWorkspace.universe_id, graph_snapshot_id: snapshotId, portfolio, risk }), onSuccess: async (item) => { setSaved(item); await client.invalidateQueries({ queryKey: ["strategies", workspaceId] }); await client.invalidateQueries({ queryKey: ["strategy-versions", item.strategy_id] }); setErrorMessage(""); }, onError: (error) => setErrorMessage(error instanceof Error ? error.message : "Could not save this version.") });

  function chooseCandidate(index: number) { setSelected(index); setExpression(candidates[index]?.expression ?? ""); setValidation(null); }
  function toggleFeature(feature: AlphaFeature) { if (!feature.available) return; setSelectedFeatures((current) => current.includes(feature.name) ? current.filter((name) => name !== feature.name) : [...current, feature.name]); }
  const contextReady = Boolean(activeWorkspace.universe_id && snapshotId);
  const live = !offline && !featureQuery.isError;
  const readySelectedFeatures = selectedFeatures.filter((name) => features.some((feature) => feature.name === name && feature.available));
  const canUseAlphaApi = live && !featureQuery.isPending && contextReady && readySelectedFeatures.length > 0;

  return <div className="alpha-studio">
    <header className="alpha-head"><div><p className="eyebrow">04 · Alpha studio</p><h1>Shape a testable hypothesis</h1><p className="alpha-lede">Select point-in-time features, ask for alternatives, then validate the strategy contract before saving a version.</p></div><span className={`alpha-source ${live ? "alpha-source-live" : ""}`}>{live ? "API connected" : "DEMO"}</span></header>
    {(offline || featureQuery.isError) && <div role="status" className="alpha-alert alpha-demo"><AlertCircle /><div><strong>{offline ? "Demo workspace" : "Feature catalog unavailable"}</strong><p>{offline ? "Candidates and feature metadata below are UI fixtures. Generation, validation, and saving require the local API." : "Showing fixture features while the API feature catalog is unavailable."}</p></div></div>}
    {errorMessage && <div role="alert" className="alpha-alert"><AlertCircle /><span>{errorMessage}</span><button aria-label="Dismiss error" onClick={() => setErrorMessage("")}><X /></button></div>}
    <section className="alpha-context card" aria-label="Research context">
      <div className="alpha-context-title"><div><span className="context-kicker">Research context</span><strong>{activeWorkspace.name}</strong></div><label><span className="sr-only">Workspace</span><select aria-label="Workspace" value={workspaceId} onChange={(event) => { setWorkspaceSelection(event.target.value); setSaved(null); setCandidates([]); }} className="field alpha-select">{(workspaces.length ? workspaces : [workspace]).map((item) => <option value={item.workspace_id} key={item.workspace_id}>{item.name}</option>)}</select></label></div>
      <div className="alpha-context-items"><div><span>Locked universe</span><strong>{activeWorkspace.universe_id ? activeWorkspace.universe_id : "Required before Alpha"}</strong></div><div><span>Graph snapshot</span><strong>{snapshotId ? `${snapshotId.slice(0, 18)} · ${graphQuery.data?.[0]?.as_of_time ?? "workspace-pinned"}` : "Required before Alpha"}</strong></div><div><span>Workspace cadence</span><strong>{activeWorkspace.cadence}</strong></div></div>
      {!contextReady && <p className="alpha-context-warning"><LockKeyhole /> Alpha generation is locked until this workspace has a locked universe and graph snapshot. <NavLink to="/universe">Review universe <ArrowRight /></NavLink></p>}
    </section>
    <div className="alpha-layout">
      <aside className="alpha-features card" aria-labelledby="feature-title"><div className="alpha-panel-head"><div><p className="eyebrow">Evidence inputs</p><h2 id="feature-title">Feature browser</h2></div><span className="alpha-count">{features.length}</span></div><label className="alpha-search"><Search /><span className="sr-only">Search features</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search features" /></label>
        {!features.length && <div className="alpha-empty">{featureQuery.isLoading ? <><LoaderCircle className="spin" /> Loading workspace catalog…</> : "No features are registered for this workspace yet."}</div>}
        <div className="alpha-feature-groups">{Object.entries(grouped).map(([category, items]) => <fieldset className="alpha-feature-group" key={category}><legend>{category}</legend>{items.map((feature) => <label className={`alpha-feature ${!feature.available ? "alpha-feature-disabled" : ""}`} key={feature.name}><input type="checkbox" checked={selectedFeatures.includes(feature.name)} disabled={!feature.available} onChange={() => toggleFeature(feature)} /><span className="alpha-feature-copy"><strong>{feature.name}</strong><span>{feature.description || "No description supplied."}</span><small>{formatFrequency(feature.frequency)} · {feature.readiness}</small>{feature.provenance.length > 0 && <small>Source: {feature.provenance.join(", ")}</small>}{!feature.available && <small className="alpha-disabled-reason">Unavailable · {feature.reason ?? "Readiness requirements are not met."}</small>}</span></label>)}</fieldset>)}</div>
        <div className="alpha-selection-summary"><strong>{selectedFeatures.length} selected</strong><span>Unavailable features cannot be selected.</span></div>
      </aside>
      <div className="alpha-main">
        <section className="card alpha-builder" aria-labelledby="builder-title"><div className="alpha-panel-head"><div><p className="eyebrow">Hypothesis</p><h2 id="builder-title">Guide the candidate search</h2></div><span className="alpha-step">01</span></div><label className="field-label" htmlFor="alpha-intent">What relationship should be tested?</label><textarea id="alpha-intent" className="field alpha-intent" value={intent} onChange={(event) => setIntent(event.target.value)} maxLength={1000} /><div className="alpha-control-grid"><label><span className="field-label">Portfolio construction</span><select className="field" value={portfolio.weighting} onChange={(event) => setPortfolio({ ...portfolio, weighting: event.target.value })}><option value="equal_weight">Equal weight</option><option value="rank_weight">Rank weight</option><option value="long_short">Long / short</option></select></label><label><span className="field-label">Maximum positions</span><input className="field" type="number" min={2} max={500} value={portfolio.max_positions} onChange={(event) => setPortfolio({ ...portfolio, max_positions: Number(event.target.value) })} /></label><label><span className="field-label">Max position weight</span><input className="field" type="number" min={0.01} max={1} step={0.01} value={risk.max_position_weight} onChange={(event) => setRisk({ ...risk, max_position_weight: Number(event.target.value) })} /></label><label className="alpha-checkbox-control"><input type="checkbox" checked={risk.sector_neutral} onChange={(event) => setRisk({ ...risk, sector_neutral: event.target.checked })} /> Sector neutral</label></div><div className="alpha-builder-footer"><span><LockKeyhole /> Point-in-time scope is pinned to the selected context</span><button className="button-primary" disabled={!canUseAlphaApi || !intent.trim() || generate.isPending} onClick={() => generate.mutate()}><Sparkles /> {generate.isPending ? "Generating…" : "Generate alternatives"}</button></div></section>
        <section className="card alpha-candidates" aria-labelledby="candidate-title"><div className="alpha-panel-head"><div><p className="eyebrow">Candidate desk</p><h2 id="candidate-title">Compare alternatives</h2></div>{candidates.length > 0 && <span className="alpha-count">{candidates.length} candidates</span>}</div>
          {!candidates.length ? <div className="alpha-empty alpha-candidate-empty"><Sparkles /><strong>Alternatives will appear here</strong><span>Generate candidates from the locked workspace context to start comparing.</span></div> : <div className="alpha-compare">{candidates.map((candidate, index) => <button key={candidate.candidate_id} className={`alpha-candidate ${selected === index ? "alpha-candidate-selected" : ""}`} aria-pressed={selected === index} onClick={() => chooseCandidate(index)}><span className="alpha-candidate-top"><span>{candidate.name}</span><small>{candidate.status}</small></span><code>{candidate.expression}</code><span className="alpha-rationale">{candidate.rationale}</span><span className="alpha-candidate-features">{candidate.feature_names.join(" · ")}</span></button>)}</div>}
          {candidates[selected] && <div className="alpha-editor"><div className="alpha-editor-head"><div><p className="eyebrow">Constrained signal DSL</p><strong>Edit the selected candidate</strong></div><button className="alpha-advanced-toggle" aria-expanded={hashPinnedExtensionsEnabled && advanced} aria-controls="alpha-python-panel" disabled={!hashPinnedExtensionsEnabled} onClick={() => setAdvanced((value) => !value)}><Code2 /> Advanced Python</button></div><label htmlFor="alpha-expression" className="sr-only">Strategy expression</label><textarea id="alpha-expression" className="alpha-expression" spellCheck={false} value={expression} onChange={(event) => { setExpression(event.target.value); setValidation(null); }} aria-describedby="dsl-help" /><div className="alpha-editor-foot"><span id="dsl-help">Registered functions only. Arbitrary code execution is not supported.</span><span>{expression.length} characters</span></div>{!hashPinnedExtensionsEnabled && <div className="alpha-advanced-disabled" role="status"><LockKeyhole /><div><strong>Advanced Python is disabled</strong><span>This runtime has not advertised the hash-pinned extension capability. The constrained signal editor remains available.</span></div></div>}{hashPinnedExtensionsEnabled && advanced && <section id="alpha-python-panel" className="alpha-python-panel" aria-label="Advanced Python extension editor"><div><strong>Python extension source</strong><p>Draft code for the reviewed, hash-pinned extension registry. The signal DSL above remains the saved strategy expression.</p></div><Suspense fallback={<div role="status" className="alpha-python-loading">Loading Python editor…</div>}><PythonEditor value={pythonDraft} onChange={setPythonDraft} /></Suspense></section>}
            {validation && <div role="status" className={`alpha-validation ${validation.ok ? "alpha-validation-ok" : "alpha-validation-failed"}`}><span>{validation.ok ? <Check /> : <AlertCircle />}</span><div><strong>{validation.ok ? "Contract validation passed" : "Contract validation did not pass"}</strong><p>{validation.message}</p><small>This is deterministic contract validation, not a backtest or performance result.</small></div></div>}
            <div className="alpha-action-row"><label className="alpha-name-field"><span className="sr-only">Strategy name</span><input className="field" value={strategyName} onChange={(event) => setStrategyName(event.target.value)} maxLength={100} /></label><div><button className="button-secondary" disabled={!contextReady || !live || validate.isPending || !expression.trim()} onClick={() => validate.mutate()}>{validate.isPending ? "Checking…" : "Validate contract"}</button><button className="button-primary" disabled={!contextReady || !live || save.isPending || !expression.trim() || !strategyName.trim()} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save version"}</button></div></div>
          </div>}
        </section>
        {saved && <section className="card alpha-history" aria-labelledby="history-title"><div className="alpha-panel-head"><div><p className="eyebrow">Strategy record</p><h2 id="history-title">Saved versions</h2></div><History /></div><div className="alpha-saved-line"><span><Check /> Saved {saved.name}</span><strong>v{saved.version || 1}</strong><time dateTime={saved.created_at}>{saved.created_at ? new Date(saved.created_at).toLocaleString() : "Just now"}</time></div>{versionsQuery.isLoading ? <p className="alpha-muted"><Clock3 /> Loading version history…</p> : versionsQuery.isError ? <p role="status" className="alpha-muted">Version history is not available from this API yet.</p> : versionsQuery.data?.map((version) => <button key={`${version.strategy_id}-${version.version}`} className="alpha-version" onClick={() => { setExpression(version.expression); setStrategyName(version.name); }}><span>Version {version.version}</span><code>{version.expression}</code><time>{version.created_at ? new Date(version.created_at).toLocaleString() : ""}</time></button>)}</section>}
      </div>
    </div>
  </div>;
}
