import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as Dialog from "@radix-ui/react-dialog";
import { Activity, ArrowRight, Atom, BarChart3, Boxes, BrainCircuit, BriefcaseBusiness, Check, ChevronRight, CircleGauge, Database, FlaskConical, Home as HomeIcon, Menu, Moon, Network, Plus, Radio, Rocket, Settings, Sun, X } from "lucide-react";
import { NavLink, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { api, type Job, type WorkspaceCreate } from "./api";
import { demoEntities, demoJobs, demoSignals, demoWorkspace } from "./demo";

type Icon = typeof HomeIcon;
type NavItem = { to: string; label: string; icon: Icon };
const workflow: NavItem[] = [
  { to: "/domain", label: "Domain", icon: BriefcaseBusiness },
  { to: "/universe", label: "Universe", icon: Boxes },
  { to: "/graph", label: "Graph", icon: Network },
  { to: "/alpha", label: "Alpha", icon: BrainCircuit },
  { to: "/backtest", label: "Backtest", icon: FlaskConical },
  { to: "/paper-export", label: "Paper / LEAN Export", icon: Rocket },
  { to: "/monitor", label: "Monitor", icon: CircleGauge },
];
const flowCopy = ["Define the thesis boundary", "Select point-in-time instruments", "Build cited relationships", "Generate constrained signals", "Test costs and unseen periods", "Run paper or package for LEAN", "Watch drift and freshness"];

function useStudioData() {
  const health = useQuery({ queryKey: ["health"], queryFn: api.health, retry: false });
  const workspaces = useQuery({ queryKey: ["workspaces"], queryFn: api.workspaces, retry: false });
  const jobs = useQuery({ queryKey: ["jobs"], queryFn: api.jobs, retry: false, refetchInterval: 5_000 });
  const offline = health.isError || workspaces.isError || jobs.isError;
  return {
    offline,
    workspaceDemo: !workspaces.data?.[0],
    workspace: workspaces.data?.[0] ?? demoWorkspace,
    jobs: jobs.data ?? demoJobs,
  };
}

export function App() {
  const data = useStudioData();
  const [dark, setDark] = useState(true);
  const [mobileNav, setMobileNav] = useState(false);
  const [jobsOpen, setJobsOpen] = useState(false);
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  const activeJobs = data.jobs.filter((job) => job.status === "queued" || job.status === "running");
  return <div className="min-h-screen bg-canvas text-ink lg:grid lg:grid-cols-[248px_1fr]">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <Sidebar open={mobileNav} onClose={() => setMobileNav(false)} offline={data.offline} />
    <div className="min-w-0"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-line bg-canvas/90 px-4 backdrop-blur md:px-8">
      <button className="icon-button lg:hidden" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu /></button>
      <div className="hidden text-xs text-muted sm:block">Autonomous research-to-strategy workspace</div>
      <div className="ml-auto flex items-center gap-2"><button className="icon-button" onClick={() => setDark((value) => !value)} aria-label={`Switch to ${dark ? "light" : "dark"} theme`}>{dark ? <Sun /> : <Moon />}</button>
        <Dialog.Root open={jobsOpen} onOpenChange={setJobsOpen}><Dialog.Trigger asChild><button className="jobs-button"><Radio /> {activeJobs.length} active {activeJobs.length === 1 ? "job" : "jobs"}</button></Dialog.Trigger><JobDrawer jobs={data.jobs} offline={data.offline} /></Dialog.Root>
      </div>
    </header><main id="main-content" className="mx-auto max-w-[1440px] px-4 py-8 md:px-8 lg:px-10"><Routes>
      <Route path="/" element={<Home offline={data.offline} activeJobs={activeJobs.length} />} />
      <Route path="/new-domain" element={<NewDomain offline={data.offline} />} />
      <Route path="/domain" element={<Domain workspaceName={data.workspace.name} demo={data.workspaceDemo} />} />
      <Route path="/universe" element={<Universe />} /><Route path="/graph" element={<Graph />} /><Route path="/alpha" element={<Alpha />} /><Route path="/backtest" element={<Backtest />} /><Route path="/paper-export" element={<PaperExport />} /><Route path="/monitor" element={<Monitor jobs={data.jobs} />} /><Route path="/settings" element={<SettingsPage offline={data.offline} />} /><Route path="*" element={<Navigate to="/" replace />} />
    </Routes></main></div>
  </div>;
}

function Sidebar({ open, onClose, offline }: { open: boolean; onClose: () => void; offline: boolean }) {
  return <><button className={`fixed inset-0 z-40 bg-black/60 lg:hidden ${open ? "block" : "hidden"}`} aria-label="Close navigation" onClick={onClose} />
    <aside className={`fixed inset-y-0 left-0 z-50 flex w-[248px] flex-col border-r border-line bg-panel p-4 transition-transform lg:sticky lg:top-0 lg:z-20 lg:h-screen ${open ? "translate-x-0" : "-translate-x-full lg:translate-x-0"}`} aria-label="Primary navigation">
      <div className="mb-7 flex items-center gap-3 px-2 py-2"><span className="grid size-9 place-items-center rounded-xl bg-violet text-sm font-black text-white">Aα</span><div><strong className="block text-sm">Agentic Alpha</strong><span className="text-xs text-muted">Studio</span></div><button className="icon-button ml-auto lg:hidden" aria-label="Close navigation" onClick={onClose}><X /></button></div>
      <nav className="space-y-1"><NavItemLink item={{ to: "/", label: "Home", icon: HomeIcon }} onClick={onClose} /><NavItemLink item={{ to: "/new-domain", label: "New Domain", icon: Plus }} onClick={onClose} /><div className="my-4 border-t border-line" /><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[0.18em] text-muted">Strategy flow</p>{workflow.map((item) => <NavItemLink key={item.to} item={item} onClick={onClose} />)}</nav>
      <div className="mt-auto space-y-2 border-t border-line pt-4"><NavItemLink item={{ to: "/settings", label: "Settings", icon: Settings }} onClick={onClose} /><div className="flex items-center gap-3 rounded-xl bg-subtle px-3 py-3 text-xs"><span className={`size-2 rounded-full ${offline ? "bg-amber" : "bg-green"}`} /><div><strong className="block">Local API</strong><span className="text-muted">{offline ? "Offline · demo fallback" : "Connected"}</span></div></div></div>
    </aside></>;
}
function NavItemLink({ item, onClick }: { item: NavItem; onClick: () => void }) { const Icon = item.icon; return <NavLink end={item.to === "/"} to={item.to} onClick={onClick} className={({ isActive }) => `nav-link ${isActive ? "nav-link-active" : ""}`}><Icon /><span>{item.label}</span></NavLink>; }

function JobDrawer({ jobs, offline }: { jobs: Job[]; offline: boolean }) {
  return <Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/65 data-[state=open]:animate-fade" /><Dialog.Content className="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto border-l border-line bg-panel p-6 shadow-2xl data-[state=open]:animate-slide-in">
    <div className="flex items-start justify-between"><div><p className="eyebrow">Operations</p><Dialog.Title className="mt-1 text-2xl font-semibold">Jobs</Dialog.Title><Dialog.Description className="mt-2 text-sm text-muted">Live API work with progress and terminal state.</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close jobs"><X /></Dialog.Close></div>
    {offline && <DemoNotice compact />}<div className="mt-6 space-y-3">{jobs.map((job) => <article className="card p-4" key={job.id}><div className="flex items-center justify-between gap-3"><strong className="text-sm capitalize">{job.kind.replaceAll("-", " ")}</strong><Status value={job.status} /></div><p className="mt-2 text-xs text-muted">{job.message ?? "No status message"}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-subtle" aria-label={`${Math.round(job.progress * 100)} percent complete`} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(job.progress * 100)}><span className="block h-full rounded-full bg-violet" style={{ width: `${job.progress * 100}%` }} /></div><p className="mt-2 font-mono text-[10px] text-muted">{Math.round(job.progress * 100)}% · {job.id.startsWith("demo-") ? "DEMO" : job.id.slice(0, 8)}</p></article>)}</div>
  </Dialog.Content></Dialog.Portal>;
}

function PageHead({ eyebrow, title, description, demo = true, action }: { eyebrow: string; title: string; description: string; demo?: boolean; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{title} {demo && <DemoBadge />}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>{action}</div>; }

function Home({ offline, activeJobs }: { offline: boolean; activeJobs: number }) {
  return <><PageHead eyebrow="Production strategy workspace" title="Agentic Alpha Studio" description="Build an evidence-bounded strategy through one autonomous, observable pipeline." demo={false} action={<NavLink className="button-primary" to="/new-domain"><Plus /> New domain</NavLink>} />{offline && <DemoNotice />}
    <section aria-labelledby="flow-title" className="mt-6"><div className="section-title"><div><p className="eyebrow">Autonomous graph</p><h2 id="flow-title">Domain to monitored strategy</h2></div><span className="text-xs text-muted">{activeJobs} active jobs{offline ? " · DEMO" : ""}</span></div><div className="workflow-grid">{workflow.map((item, index) => { const Icon = item.icon; return <NavLink to={item.to} key={item.to} className="workflow-card"><div className="flex items-center justify-between"><span className="workflow-icon"><Icon /></span><span className="font-mono text-[10px] text-muted">0{index + 1}</span></div><strong>{item.label}</strong><span className="text-xs text-muted">{flowCopy[index]}</span><ChevronRight className="ml-auto mt-auto text-muted" /></NavLink>; })}</div></section>
    <div className="mt-7 grid gap-4 xl:grid-cols-[1.35fr_1fr]"><Panel title="Strategy telemetry" label="DEMO"><div className="metric-grid"><Metric label="Signals validating" value="03" icon={BrainCircuit} /><Metric label="Graph coverage" value="68%" icon={Network} /><Metric label="OOS score" value="B+" icon={BarChart3} /></div></Panel><Panel title="Latest autonomous activity" label="DEMO"><Timeline /></Panel></div>
  </>;
}

function NewDomain({ offline }: { offline: boolean }) {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [error, setError] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: async (input: WorkspaceCreate) => { const workspace = await api.createWorkspace(input); await api.bootstrapWorkspace(workspace.workspace_id); return workspace; }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["workspaces"] }); await queryClient.invalidateQueries({ queryKey: ["jobs"] }); navigate("/domain"); }, onError: (reason) => setError(reason instanceof Error ? reason.message : "Could not create workspace") });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const values = new FormData(event.currentTarget); const input: WorkspaceCreate = { name: String(values.get("name")), domain: String(values.get("domain")), base_currency: "USD", cadence: "daily", regions: String(values.get("regions")).split(",").map((v) => v.trim()).filter(Boolean), status: "building" }; if (offline) { navigate("/domain"); return; } mutation.mutate(input); }
  return <><PageHead eyebrow="Domain" title="Create a strategy domain" description="Set the economic boundary. The graph then advances autonomously through universe, evidence, alpha, validation, paper/export, and monitoring." demo={offline} /><form className="card max-w-3xl space-y-5 p-6 sm:p-8" onSubmit={submit}><Field label="Workspace name" name="name" placeholder="Semiconductor Core" /><Field label="Domain thesis" name="domain" placeholder="Global semiconductor supply-chain dependencies" /><Field label="Regions" name="regions" placeholder="US, TW, NL, KR" hint="Comma-separated ISO country codes" />{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<div className="flex flex-col gap-3 border-t border-line pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted">{offline ? "Offline: this opens the labeled demo workspace." : "Creates the workspace and starts its bootstrap job."}</p><button className="button-primary" disabled={mutation.isPending}>{mutation.isPending ? "Creating…" : offline ? "Open demo domain" : "Create and start"}<ArrowRight /></button></div></form></>;
}

function Domain({ workspaceName, demo }: { workspaceName: string; demo: boolean }) { return <><PageHead eyebrow="01 · Domain" title={workspaceName} description="A durable boundary for one production strategy, its evidence, and every reproducible run." demo={demo} action={<Next to="/universe">Continue to Universe</Next>} /><div className="grid gap-4 lg:grid-cols-3"><MetricCard label="Status" value={demo ? "Ready · DEMO" : "Ready"} icon={Check} /><MetricCard label="Cadence" value="Daily · DEMO" icon={Activity} /><MetricCard label="Base currency" value="USD · DEMO" icon={Database} /></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><Panel title="Autonomous objective" label="DEMO"><p className="copy">Map production dependencies, derive bounded graph features, challenge factor candidates, and carry only validated outputs into paper execution.</p></Panel><Panel title="Safeguards" label="DEMO"><ul className="check-list"><li><Check /> Point-in-time inputs enforced</li><li><Check /> Constrained signal expressions</li><li><Check /> Paper-only runtime</li></ul></Panel></div></>; }
function Universe() { return <><PageHead eyebrow="02 · Universe" title="Point-in-time universe" description="The instruments this strategy may evaluate, selected under an explicit as-of time." action={<Next to="/graph">Build Graph</Next>} /><div className="entity-grid">{demoEntities.map((name, index) => <article className="card flex items-center gap-3 p-4" key={name}><span className="grid size-10 place-items-center rounded-xl bg-violet/10 font-mono text-xs text-violet">{name.slice(0, 2).toUpperCase()}</span><div><strong className="block text-sm">{name}</strong><span className="text-xs text-muted">{index > 7 ? "Equipment" : "Core company"} · DEMO</span></div></article>)}</div></>; }
function Graph() { return <><PageHead eyebrow="03 · Graph" title="Autonomous evidence graph" description="Agents continuously collect, corroborate, score, and version relationships inside the domain boundary." action={<Next to="/alpha">Generate Alpha</Next>} /><div className="grid gap-4 lg:grid-cols-[1.4fr_0.8fr]"><div className="graph-card" role="img" aria-label="Demo relationship graph connecting NVDA, TSMC, ASML, and AMD"><div className="graph-line line-a" /><div className="graph-line line-b" /><GraphNode className="left-[12%] top-[38%]" name="NVDA" /><GraphNode className="left-[46%] top-[17%]" name="TSMC" /><GraphNode className="right-[10%] top-[47%]" name="ASML" /><GraphNode className="bottom-[10%] left-[42%]" name="AMD" /></div><Panel title="Selected relationship" label="DEMO"><p className="eyebrow">Manufacturing dependency</p><h2 className="mt-3 text-2xl">NVDA → TSMC</h2><div className="mt-6 space-y-4"><Scale label="Confidence" value={91} /><Scale label="Dependency" value={82} /><Scale label="Substitutability" value={24} /></div><p className="mt-6 text-xs leading-5 text-muted">3 corroborating sources · versioned evidence trail · no manual review queue</p></Panel></div></>; }
function Alpha() { return <><PageHead eyebrow="04 · Alpha" title="Alpha generator" description="Transform graph features into constrained, testable strategy candidates without arbitrary code execution." action={<Next to="/backtest">Run Backtest</Next>} /><div className="grid gap-4 lg:grid-cols-2"><Panel title="Strategy intent" label="DEMO"><label className="field-label" htmlFor="intent">Challenge</label><textarea id="intent" className="field min-h-32" defaultValue="Test whether supply-chain ripple risk explains next-period cross-sectional returns." /><div className="mt-3 flex flex-wrap gap-2">{["graph_ripple_risk", "dependency_strength", "market_return"].map((value) => <span className="chip" key={value}>{value}</span>)}</div></Panel><Panel title="Generated candidates" label="DEMO"><Candidate expression="Rank(graph_ripple_risk)" status="Backtest queued" /><Candidate expression="−Rank(dependency_strength)" status="Constraint check passed" /></Panel></div></>; }
function Backtest() { return <><PageHead eyebrow="05 · Backtest" title="Validation lab" description="Evaluate costs, baselines, leakage controls, and chronological holdouts before a strategy can advance." action={<Next to="/paper-export">Paper / LEAN Export</Next>} /><div className="metric-grid"><MetricCard label="Rank IC" value="0.14 · DEMO" icon={BarChart3} /><MetricCard label="Net return" value="+8.4% · DEMO" icon={Activity} /><MetricCard label="Max drawdown" value="−6.2% · DEMO" icon={CircleGauge} /></div><Panel title="Deterministic validation" label="DEMO"><ul className="check-list"><li><Check /> Point-in-time data passed</li><li><Check /> Baseline comparison passed</li><li><Check /> Transaction costs included</li><li><Check /> OOS threshold passed</li></ul></Panel></>; }
function PaperExport() { return <><PageHead eyebrow="06 · Paper / LEAN Export" title="Strategy output" description="Run a validated strategy in the paper environment or package its reproducible contract for LEAN." action={<Next to="/monitor">Open Monitor</Next>} /><div className="grid gap-4 lg:grid-cols-2"><Panel title="Paper strategy" label="DEMO"><Output icon={Radio} title="Capacity ripple v0.3" copy="Autonomous paper target generation. No broker credentials and no live orders." action="Open paper portfolio" /></Panel><Panel title="LEAN package" label="DEMO"><Output icon={Rocket} title="Engine-neutral export" copy="Versioned strategy, data, graph, and risk manifests prepared for LEAN." action="Configure export" /></Panel></div></>; }
function Monitor({ jobs }: { jobs: Job[] }) { return <><PageHead eyebrow="07 · Monitor" title="Strategy monitor" description="Observe freshness, drift, job health, and deterministic safeguards after deployment." /><div className="grid gap-4 lg:grid-cols-3">{demoSignals.map((signal) => <article className="card p-5" key={signal.name}><div className="flex items-start justify-between"><div><strong className="block">{signal.name}</strong><span className="text-xs text-muted">{signal.state} · DEMO</span></div><span className="font-mono text-sm">{signal.health}%</span></div><div className="mt-5 h-2 overflow-hidden rounded bg-subtle"><span className="block h-full bg-violet" style={{ width: `${signal.health}%` }} /></div></article>)}</div><div className="mt-5"><Panel title="Runtime jobs" label={jobs.some((job) => job.id.startsWith("demo-")) ? "DEMO" : "LIVE"}>{jobs.map((job) => <div className="flex items-center gap-3 border-t border-line py-3 first:border-0" key={job.id}><Activity className="text-violet" /><div className="flex-1"><strong className="block text-sm capitalize">{job.kind.replaceAll("-", " ")}</strong><span className="text-xs text-muted">{job.message}</span></div><Status value={job.status} /></div>)}</Panel></div></>; }
function SettingsPage({ offline }: { offline: boolean }) { return <><PageHead eyebrow="System" title="Settings" description="Local runtime and research policy status." demo={false} /><Panel title="Environment"><dl className="settings-list"><div><dt>Local API</dt><dd>{offline ? "Offline · demo fallback active" : "Connected"}</dd></div><div><dt>Execution</dt><dd>Paper only</dd></div><div><dt>Research flow</dt><dd>Autonomous, observable, deterministic gates</dd></div></dl></Panel></>; }

function Panel({ title, label, children }: { title: string; label?: string; children: ReactNode }) { return <section className="card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold">{title}</h2>{label && <span className="demo-badge">{label}</span>}</div>{children}</section>; }
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: Icon }) { return <div className="rounded-xl bg-subtle p-4"><Icon className="mb-5 text-violet" /><span className="block text-xs text-muted">{label}</span><strong className="mt-1 block text-2xl">{value}</strong></div>; }
function MetricCard({ label, value, icon: Icon }: { label: string; value: string; icon: Icon }) { return <article className="card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-xl bg-violet/10 text-violet"><Icon /></span><div><span className="block text-xs text-muted">{label}</span><strong className="mt-1 block">{value}</strong></div></article>; }
function DemoNotice({ compact = false }: { compact?: boolean }) { return <div className={`demo-notice ${compact ? "mt-5" : ""}`}><Atom /><div><strong>Demo fallback</strong><p>The local API is unavailable. Every value shown below is a labeled UI fixture.</p></div></div>; }
function DemoBadge() { return <span className="demo-badge align-middle">DEMO</span>; }
function Next({ to, children }: { to: string; children: ReactNode }) { return <NavLink className="button-primary" to={to}>{children}<ArrowRight /></NavLink>; }
function Field({ label, name, placeholder, hint }: { label: string; name: string; placeholder: string; hint?: string }) { const hintId = `${name}-hint`; return <div><label className="field-label" htmlFor={name}>{label}</label><input id={name} className="field mt-2" name={name} placeholder={placeholder} aria-describedby={hint ? hintId : undefined} required />{hint && <span id={hintId} className="mt-2 block text-xs font-normal text-muted">{hint}</span>}</div>; }
function Status({ value }: { value: Job["status"] }) { return <span className={`status status-${value}`}>{value}</span>; }
function Timeline() { return <div className="space-y-4">{[[Network, "Graph snapshot versioned", "10:42 · DEMO"], [BrainCircuit, "Alpha candidate advanced", "09:18 · DEMO"], [Database, "Point-in-time panel refreshed", "Yesterday · DEMO"]].map(([TimelineIcon, title, time]) => { const TIcon = TimelineIcon as Icon; return <div className="flex items-center gap-3" key={String(title)}><span className="grid size-9 place-items-center rounded-xl bg-violet/10 text-violet"><TIcon /></span><div><strong className="block text-sm">{String(title)}</strong><span className="text-xs text-muted">{String(time)}</span></div></div>; })}</div>; }
function GraphNode({ className, name }: { className: string; name: string }) { return <div className={`absolute z-10 grid size-16 place-items-center rounded-full border border-violet/50 bg-panel font-mono text-xs shadow-[0_0_35px_rgba(139,92,246,.2)] ${className}`}>{name}</div>; }
function Scale({ label, value }: { label: string; value: number }) { return <div><div className="mb-2 flex justify-between text-xs"><span className="text-muted">{label}</span><strong>{value}%</strong></div><div className="h-1.5 rounded bg-subtle"><span className="block h-full rounded bg-violet" style={{ width: `${value}%` }} /></div></div>; }
function Candidate({ expression, status }: { expression: string; status: string }) { return <article className="border-t border-line py-4 first:border-0"><code className="text-sm text-violet">{expression}</code><p className="mt-2 text-xs text-muted">{status} · DEMO</p></article>; }
function Output({ icon: Icon, title, copy, action }: { icon: Icon; title: string; copy: string; action: string }) { return <div><span className="grid size-12 place-items-center rounded-xl bg-violet/10 text-violet"><Icon /></span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy}</p><button className="button-secondary mt-6">{action}<ArrowRight /></button></div>; }
